apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-lost-hospital
  namespace: lost-hospital
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: "lost-hospital.ddns.net"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: svc-lost-hospital
              port: 
                number: 8080